apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: devops-project
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Ahtesham-Shah999/FLUX-CD-Devops.git
  ref:
    branch: main
